# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(1366, 768)
        mainWindow.setMinimumSize(QtCore.QSize(1366, 768))
        mainWindow.setMaximumSize(QtCore.QSize(1366, 768))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(10)
        mainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(mainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(290, 20, 111, 71))
        self.label.setStyleSheet("image: url(:/icon/icon.ico);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(140, 90, 441, 81))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 140, 651, 131))
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.diagnosa = QtWidgets.QPushButton(self.centralwidget)
        self.diagnosa.setGeometry(QtCore.QRect(620, 280, 100, 50))
        self.diagnosa.setIconSize(QtCore.QSize(30, 25))
        self.diagnosa.setObjectName("diagnosa")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(620, 380, 100, 50))
        self.pushButton_2.setIconSize(QtCore.QSize(30, 25))
        self.pushButton_2.setObjectName("pushButton_2")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 290, 279, 44))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_31 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_31.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_31.setObjectName("horizontalLayout_31")
        self.g1y = QtWidgets.QRadioButton(self.layoutWidget)
        self.g1y.setObjectName("g1y")
        self.horizontalLayout_31.addWidget(self.g1y)
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(10, 600, 289, 39))
        self.label_9.setObjectName("label_9")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(10, 520, 289, 44))
        self.label_8.setObjectName("label_8")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(10, 430, 289, 50))
        self.label_7.setObjectName("label_7")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(10, 330, 289, 56))
        self.label_4.setObjectName("label_4")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(10, 240, 289, 65))
        self.label_6.setObjectName("label_6")
        self.layoutWidget1 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 380, 279, 44))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_32 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_32.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_32.setObjectName("horizontalLayout_32")
        self.g2y = QtWidgets.QRadioButton(self.layoutWidget1)
        self.g2y.setObjectName("g2y")
        self.horizontalLayout_32.addWidget(self.g2y)
        self.layoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget_2.setGeometry(QtCore.QRect(10, 470, 279, 44))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.horizontalLayout_33 = QtWidgets.QHBoxLayout(self.layoutWidget_2)
        self.horizontalLayout_33.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_33.setObjectName("horizontalLayout_33")
        self.g3y = QtWidgets.QRadioButton(self.layoutWidget_2)
        self.g3y.setObjectName("g3y")
        self.horizontalLayout_33.addWidget(self.g3y)
        self.layoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget_3.setGeometry(QtCore.QRect(10, 550, 279, 44))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.horizontalLayout_34 = QtWidgets.QHBoxLayout(self.layoutWidget_3)
        self.horizontalLayout_34.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_34.setObjectName("horizontalLayout_34")
        self.g4y = QtWidgets.QRadioButton(self.layoutWidget_3)
        self.g4y.setObjectName("g4y")
        self.horizontalLayout_34.addWidget(self.g4y)
        self.layoutWidget_4 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget_4.setGeometry(QtCore.QRect(10, 630, 279, 44))
        self.layoutWidget_4.setObjectName("layoutWidget_4")
        self.horizontalLayout_35 = QtWidgets.QHBoxLayout(self.layoutWidget_4)
        self.horizontalLayout_35.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_35.setObjectName("horizontalLayout_35")
        self.g5y = QtWidgets.QRadioButton(self.layoutWidget_4)
        self.g5y.setObjectName("g5y")
        self.horizontalLayout_35.addWidget(self.g5y)
        self.layoutWidget_5 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget_5.setGeometry(QtCore.QRect(310, 470, 279, 44))
        self.layoutWidget_5.setObjectName("layoutWidget_5")
        self.horizontalLayout_36 = QtWidgets.QHBoxLayout(self.layoutWidget_5)
        self.horizontalLayout_36.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_36.setObjectName("horizontalLayout_36")
        self.g8y = QtWidgets.QRadioButton(self.layoutWidget_5)
        self.g8y.setObjectName("g8y")
        self.horizontalLayout_36.addWidget(self.g8y)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(310, 330, 289, 56))
        self.label_5.setObjectName("label_5")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(310, 520, 289, 44))
        self.label_13.setObjectName("label_13")
        self.layoutWidget_6 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget_6.setGeometry(QtCore.QRect(310, 630, 279, 44))
        self.layoutWidget_6.setObjectName("layoutWidget_6")
        self.horizontalLayout_37 = QtWidgets.QHBoxLayout(self.layoutWidget_6)
        self.horizontalLayout_37.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_37.setObjectName("horizontalLayout_37")
        self.g10y = QtWidgets.QRadioButton(self.layoutWidget_6)
        self.g10y.setObjectName("g10y")
        self.horizontalLayout_37.addWidget(self.g10y)
        self.layoutWidget_7 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget_7.setGeometry(QtCore.QRect(310, 550, 279, 44))
        self.layoutWidget_7.setObjectName("layoutWidget_7")
        self.horizontalLayout_38 = QtWidgets.QHBoxLayout(self.layoutWidget_7)
        self.horizontalLayout_38.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_38.setObjectName("horizontalLayout_38")
        self.g9y = QtWidgets.QRadioButton(self.layoutWidget_7)
        self.g9y.setObjectName("g9y")
        self.horizontalLayout_38.addWidget(self.g9y)
        self.layoutWidget_8 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget_8.setGeometry(QtCore.QRect(310, 380, 279, 44))
        self.layoutWidget_8.setObjectName("layoutWidget_8")
        self.horizontalLayout_39 = QtWidgets.QHBoxLayout(self.layoutWidget_8)
        self.horizontalLayout_39.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_39.setObjectName("horizontalLayout_39")
        self.g7y = QtWidgets.QRadioButton(self.layoutWidget_8)
        self.g7y.setObjectName("g7y")
        self.horizontalLayout_39.addWidget(self.g7y)
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(310, 600, 289, 39))
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.centralwidget)
        self.label_16.setGeometry(QtCore.QRect(310, 430, 289, 50))
        self.label_16.setObjectName("label_16")
        self.layoutWidget_9 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget_9.setGeometry(QtCore.QRect(310, 290, 279, 44))
        self.layoutWidget_9.setObjectName("layoutWidget_9")
        self.horizontalLayout_40 = QtWidgets.QHBoxLayout(self.layoutWidget_9)
        self.horizontalLayout_40.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_40.setObjectName("horizontalLayout_40")
        self.g6y = QtWidgets.QRadioButton(self.layoutWidget_9)
        self.g6y.setObjectName("g6y")
        self.horizontalLayout_40.addWidget(self.g6y)
        self.label_17 = QtWidgets.QLabel(self.centralwidget)
        self.label_17.setGeometry(QtCore.QRect(310, 240, 289, 65))
        self.label_17.setObjectName("label_17")
        self.deskripsi = QtWidgets.QTextEdit(self.centralwidget)
        self.deskripsi.setGeometry(QtCore.QRect(800, 10, 551, 361))
        self.deskripsi.setObjectName("deskripsi")
        self.penanganan = QtWidgets.QTextEdit(self.centralwidget)
        self.penanganan.setGeometry(QtCore.QRect(800, 390, 551, 361))
        self.penanganan.setObjectName("penanganan")
        mainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(mainWindow)
        self.statusbar.setObjectName("statusbar")
        mainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(mainWindow)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "EXPERT SYSTEM"))
        self.label_3.setText(_translate("mainWindow", "HEADACHE EXPERT SYSTEM"))
        self.label_2.setText(_translate("mainWindow", "APLIKASI EXPERT SYSTEM BERBASIS BAHASA PYTHON\n"
"ISILAH GEJALA-GEJALA YANG DIMILIKI OLEH PASIEN DENGAN JUJUR\n"
"CUKUP ISI GEJALA YANG DIDERITA!"))
        self.diagnosa.setText(_translate("mainWindow", "DIAGNOSA"))
        self.pushButton_2.setText(_translate("mainWindow", "RESET"))
        self.g1y.setText(_translate("mainWindow", "Ya"))
        self.label_9.setText(_translate("mainWindow", "5. Mata Merah?"))
        self.label_8.setText(_translate("mainWindow", "4. Nyeri Kepala Terpusat Pada Mata?"))
        self.label_7.setText(_translate("mainWindow", "3. Pusing Berputar?"))
        self.label_4.setText(_translate("mainWindow", "2. Nyeri Otot Leher?"))
        self.label_6.setText(_translate("mainWindow", "1. Lelah?"))
        self.g2y.setText(_translate("mainWindow", "Ya"))
        self.g3y.setText(_translate("mainWindow", "Ya"))
        self.g4y.setText(_translate("mainWindow", "Ya"))
        self.g5y.setText(_translate("mainWindow", "Ya"))
        self.g8y.setText(_translate("mainWindow", "Ya"))
        self.label_5.setText(_translate("mainWindow", "7. Nyeri Seperti Tertekan?"))
        self.label_13.setText(_translate("mainWindow", "9. Konsentrasi Terganggu?"))
        self.g10y.setText(_translate("mainWindow", "Ya"))
        self.g9y.setText(_translate("mainWindow", "Ya"))
        self.g7y.setText(_translate("mainWindow", "Ya"))
        self.label_15.setText(_translate("mainWindow", "10. Sulit Tidur / Susah Bangun?"))
        self.label_16.setText(_translate("mainWindow", "8. Gelisah?"))
        self.g6y.setText(_translate("mainWindow", "Ya"))
        self.label_17.setText(_translate("mainWindow", "6. Air Mata Keluar?"))
        self.deskripsi.setHtml(_translate("mainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Roboto\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">DESKRIPSI PENYAKIT</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.penanganan.setHtml(_translate("mainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Roboto\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">PENANGANAN PENYAKIT</p></body></html>"))
import resource_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    mainWindow = QtWidgets.QMainWindow()
    ui = Ui_mainWindow()
    ui.setupUi(mainWindow)
    mainWindow.show()
    sys.exit(app.exec_())
